export default {
    teams: [
        {id: 1, name: 'Não tenho time preferido'},
        {id: 2, name: 'Athletico Paranaense'},
        {id: 3, name: 'Atlético Mineiro'},
        {id: 4, name: 'Avai'},
        {id: 5, name: 'Bahia'},
        {id: 6, name: 'Botafogo'},
        {id: 7, name: 'Ceara'},
        {id: 8, name: 'Chapecoense'},
        {id: 9, name: 'Corinthians'},
        {id: 10, name: 'Cruzeiro'},
        {id: 11, name: 'Csa'},
        {id: 12, name: 'Flamengo'},
        {id: 13, name: 'Fluminense'},
        {id: 14, name: 'Fortaleza'},
        {id: 15, name: 'Goias'},
        {id: 16, name: 'Gremio'},
        {id: 17, name: 'Internacional'},
        {id: 18, name: 'Palmeiras'},
        {id: 19, name: 'Santos'},
        {id: 20, name: 'Sao Paulo'},
        {id: 21, name: 'Vasco da Gama'},
    ],
    // teamsName: [
    //     'Não tenho time preferido',
    //     'Athletico Paranaense',
    //     'Atlético Mineiro',
    //     'Avai',
    //     'Bahia',
    //     'Botafogo',
    //     'Ceara',
    //     'Chapecoense',
    //     'Corinthians',
    //     'Cruzeiro',
    //     'Csa',
    //     'Flamengo',
    //     'Fluminense',
    //     'Fortaleza',
    //     'Goias',
    //     'Gremio',
    //     'Internacional',
    //     'Palmeiras',
    //     'Santos',
    //     'Sao Paulo',
    //     'Vasco da Gama'
    // ]
}
